<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FarmIQ.Application\FarmIQ.Application.csproj" />
    <ProjectReference Include="..\FarmIQ.Core\FarmIQ.Core.csproj" />
    <ProjectReference Include="..\FarmIQ.Shared\FarmIQ.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="5.8.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="5.8.0" />
    <PackageReference Include="OpenIddict.Server" Version="5.8.0" />
    <PackageReference Include="OpenIddict.Validation" Version="5.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
